services:
  foxogram-docs:
    build:
      context: .
    restart: always
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.foxogram-docs.rule: Host(`docs.foxogram.su`)
      traefik.http.routers.foxogram-docs.tls.certresolver: letsencrypt
      traefik.http.services.foxogram-docs.loadbalancer.server.port: 80

networks:
  traefik:
    external: true
